function Zkc(){}
function blc(){}
function elc(){}
function h7b(a,b){a.d=b}
function Skc(a){this.b=a}
function Okc(){R8b.call(this)}
function j_b(a){LYb.call(this);this.b=a}
function glc(){glc=$Kc;Xkc=new blc}
function hlc(){hlc=$Kc;Ykc=new elc}
function Vkc(){Vkc=$Kc;Ukc=new Zkc}
var MSc='bottomColor',LSc='topColor';$T(909,902,{281:1,288:1},j_b);_.Qe=function l_b(){return null};$T(1129,1,KMc);_.Db=function Mkc(){r8b(this.c,new Okc(this.b))};$T(1130,961,{},Okc);_.ob=function Pkc(){var a,b,c,d,e;this.b=new GPb(40,sGb(this.H.n),1,10000);g5b(this.b.ab,700,180,-500);w7b(this.I,new m7b(16448250,1000,10000));this.c=new Bwb(this.b,this.H.d);i5b(this.c.w,150);a=new IXb(16777215,1.475);g5b(a.ab,100,100,-100);GOb(this.I,a);b=new RXb(16777215,16777215,1.25);o2b(b.M,0.6,1,0.75);o2b(b.b,0.1,0.8,0.7);x4b(b.ab,500);GOb(this.I,b);e=new D1b((Vkc(),Ukc));IYb(e,(u$b(),r$b));dIb(xYb(e),LSc,new kMb((DMb(),oMb),new s2b(30719)));dIb(xYb(e),MSc,new kMb(oMb,new s2b(16777215)));dIb(xYb(e),LSc,new kMb(oMb,h2b(b.M)));dIb(xYb(e),NSc,new kMb(pMb,new Ejb(400)));dIb(xYb(e),'exponent',new kMb(pMb,new Ejb(0.6)));h7b(this.I.c,h2b(Fu(Fu(cRb(xYb(e).j,MSc),225).e,293)));d=new ZVb(4000,32,15);c=new K6b(d,e);GOb(this.I,c);QGb(this.H.n,this.I.c.d,1);this.H.n.bb=true;this.H.n.cb=true;new Mxc('./static/models/obj/lightmap/lightmap.js',new Skc(this))};_.pb=function Qkc(a){zwb(this.c);EGb(this.H.n,this.I,this.b,null,false)};$T(1131,1,{},Skc);_.Bf=function Tkc(a,b){var c;c=new K6b(b,new j_b(Fu(a,338).b));f5b(c.ab,0);f5b(c.fb,100);GOb(this.b.I,c)};var Ukc;$T(1132,1,{},Zkc);_.Qd=function $kc(){return glc(),Xkc};_.Rd=function _kc(){return hlc(),Ykc};var Xkc,Ykc;$T(1133,1,{},blc);_.pc=function clc(){return 'uniform vec3 topColor;\nuniform vec3 bottomColor;\nuniform float offset;\nuniform float exponent;\n\nvarying vec3 worldPosition;\n\nvoid main() {\n\n\tfloat h = normalize( worldPosition + offset ).y;\n\tgl_FragColor = vec4( mix( bottomColor, topColor, max( pow( h, exponent ), 0.0 ) ), 1.0 );\n\n}'};$T(1134,1,{},elc);_.pc=function flc(){return 'varying vec3 worldPosition;\n\nvoid main() {\n\n\tvec4 mPosition = modelMatrix * vec4( position, 1.0 );\n\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\tworldPosition = mPosition.xyz;\n\n}'};var NM=sjb(FRc,'MaterialsLightmap$DemoScene',1130),MM=sjb(FRc,'MaterialsLightmap$DemoScene$1',1131),WI=sjb(OSc,'MeshFaceMaterial',909),QM=sjb(FRc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator',1132),OM=sjb(FRc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator$1',1133),PM=sjb(FRc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator$2',1134);YMc(Hi)(19);