function Z7(){}
function pzb(){}
function TFb(){}
function Jsb(a){a.c=5;a.d=5}
function $Fb(){$Fb=hLb;bGb()}
function UFb(){xAb.call(this)}
function _Z(a){return 85<a?85:a}
function bGb(){bGb=hLb;_Fb=$moduleBase+C3b}
function Jpb(a,b){ctb(a.N,1,0,0);Ipb(a,b,a.N)}
function Kpb(a,b){ctb(a.N,0,1,0);Ipb(a,b,a.N)}
function Lpb(a,b){ctb(a.N,0,0,1);Ipb(a,b,a.N)}
function Ipb(a,b,c){jsb(a.y,c);c.Fd(b);a.F.yd(c)}
function qzb(){mzb.call(this,11193599);this.a=6.99999975040555E-4}
function cGb(){cGb=hLb;bGb();aGb=new NF((BG(),new xG(_Fb)),0,512,512)}
function jsb(a,b){var c,d,e;c=b.c;d=b.d;e=b.b;Ksb(b,a.a[0]*c+a.a[4]*d+a.a[8]*e);Lsb(b,a.a[1]*c+a.a[5]*d+a.a[9]*e);dtb(b,a.a[2]*c+a.a[6]*d+a.a[10]*e);b.Gd();return b}
function _7(a,b){X7.call(this,a,b);this.u=~~(Mf(b.A,w3b)/2);this.v=~~(Mf(b.A,x3b)/2);jw!=Wt&&(this.x.A.setAttribute(y3b,z3b),undefined);this.s=new ftb;xI(this.x,this,(gk(),gk(),fk));xI(this.x,this,(jl(),jl(),il));xI(this.x,this,(cl(),cl(),bl));xI(this.x,this,(ql(),ql(),pl));xI((DT(),HT(null)),this,(Jk(),Jk(),Ik));xI(HT(null),this,(Qk(),Qk(),Pk))}
function $7(a,b){var c,d,e,f;if(a.b){return}else{a.a=0;d=b*a.q;a.k&&Lpb(a.w,-(d+a.a));a.i&&Lpb(a.w,d);a.n&&Jpb(a.w,-d);a.o&&Jpb(a.w,d);a.p&&Kpb(a.w,d);a.j&&Kpb(a.w,-d);c=b*a.e;a.d+=a.f*c;a.c-=a.g*c;a.c=YZ(-85,_Z(a.c));a.r=(90-a.c)*3.141592653589793/180;a.t=a.d*3.141592653589793/180;f=a.s;e=a.w.F;Ksb(f,e.c+100*c$(a.r)*VZ(a.t));Lsb(f,e.d+100*VZ(a.r));dtb(f,e.b+100*c$(a.r)*c$(a.t))}a.d+=a.f*c;a.c-=a.g*c;a.c=YZ(-85,_Z(a.c));a.r=(90-a.c)*3.141592653589793/180;a.t=a.d*3.141592653589793/180;f=a.s;e=a.w.F;Ksb(f,e.c+100*c$(a.r)*VZ(a.t));Lsb(f,e.d+100*VZ(a.r));dtb(f,e.b+100*c$(a.r)*c$(a.t));Wpb(a.w,f)}
var C3b='389241B6D3B7F8982E24847648BC36AA.cache.jpg',B3b=':fogDensity',E3b='FirstPersonControl',F3b='GeometryDynamic$DemoScene';_=_7.prototype=Z7.prototype=new W7;_.gC=function a8(){return lw};_.xb=function b8(a){eg(a.a)};_.zb=function c8(a){switch(a.a.keyCode||0){case 38:case 87:this.k=true;break;case 37:case 65:this.n=true;break;case 40:case 83:this.i=true;break;case 39:case 68:this.o=true;break;case 82:this.p=true;break;case 70:this.j=true;break;case 81:this.b=!this.b;}};_.Ab=function d8(a){switch(a.a.keyCode||0){case 38:case 87:this.k=false;break;case 37:case 65:this.n=false;break;case 40:case 83:this.i=false;break;case 39:case 68:this.o=false;break;case 82:this.p=false;break;case 70:this.j=false;}};_.Cb=function e8(a){eg(a.a);fg(a.a);switch(a.a.button||0){case 1:this.k=true;break;case 2:this.i=true;}};_.Db=function f8(a){if(jw==Wt){this.f=Xj(a)-this.u;this.g=Yj(a)-this.v}else{this.f=Xj(a)-ng(this.x.A)-this.u;this.g=Yj(a)-og(this.x.A)-this.v}};_.Eb=function g8(a){eg(a.a);fg(a.a);switch(a.a.button||0){case 1:this.k=false;break;case 2:this.i=false;}};_.cM={16:1,19:1,20:1,22:1,23:1,24:1,36:1};_.a=0;_.b=false;_.c=0;_.d=0;_.e=0.004999999888241291;_.f=0;_.g=0;_.i=false;_.j=false;_.k=false;_.n=false;_.o=false;_.p=false;_.q=1;_.r=0;_.s=null;_.t=0;_.u=0;_.v=0;_=qzb.prototype=pzb.prototype=new lzb;_.gC=function rzb(){return hz};_.Rd=function szb(a){Cp(a.e[A3b],127).e=this.c;Cp(a.e[B3b],127).e=new mZ(this.a)};_.a=0;_=OFb.prototype;_.kb=function SFb(){tAb(this.b,new UFb(this.a))};_=UFb.prototype=TFb.prototype=new wAb;_.gC=function VFb(){return lA};_.dd=function WFb(){B7(this,new qqb(60,J7(this.q.C),1,20000))};_.bb=function XFb(){var a,b,c,d,e;this.p.F.d=200;Fpb(this.s,this.p);zzb(this.s,new qzb);this.a=new _7(this.p,this.q.C);this.a.q=500;this.a.e=0.10000000149011612;this.b=new Uub(20000,20000,127,127);this.b.g=true;for(a=0,b=this.b.B.b;a<b;++a)Lsb(Cp(A2(this.b.B,a),144),35*Math.sin(a/2));rrb(this.b,(HY(),HY(),FY));trb(this.b);e=Fzb(($Fb(),cGb(),bGb(),aGb),null);sob(e,(ahb(),_gb));tob(e,_gb);Jsb(e.r);d=new rxb;d.g=new Fqb(17663);d.j=e;c=new mxb(d);this.c=new Tyb(this.b,c);Fpb(this.s,this.c);this.d=Sc()};_.bd=function YFb(){};_.cb=function ZFb(a){var b,c;for(b=0,c=this.b.B.b;b<c;++b)Lsb(Cp(A2(this.b.B,b),144),35*Math.sin(b/5+(a*0.01+b)/7));this.c.f.C=true;$7(this.a,(Sc()-this.d)*0.001);this.d=Sc();A7(this)};_.a=null;_.b=null;_.c=null;_.d=0;var _Fb,aGb=null;var lw=TY(D3b,E3b),lA=TY(L1b,F3b);jLb(Md)(8);