function zlc(){}
function Dlc(){}
function Glc(){}
function eGb(a,b){a.e=b}
function rlc(){_6b.call(this)}
function vlc(){vlc=NEc;ulc=new zlc}
function Ilc(){Ilc=NEc;xlc=new Dlc}
function Jlc(){Jlc=NEc;ylc=new Glc}
function CGb(a,b){!a.a&&(a.a=new HPb);a.a.nd(aKc,b)}
function qlc(a){var b,c;c=new Uob;for(b=0;b<a.i.Pc();b++){qu(a.i.Hc(b),240);Job(c,b,new qpb(gu(HR,mGc,298,[new y3b(1,0,0),new y3b(0,1,0),new y3b(0,0,1)])))}return c}
NS(1159,1,vGc);_.zb=function olc(){B6b(this.b,new rlc(this.a))};NS(1160,959,{},rlc);_.nb=function slc(){var a,b,c,d,e,f,g,i;this.a=new eOb(40,SEb(this.D.k),1,2000);u3b(this.a._,800);c=new ITb(150,150,150);d=new ITb(150,150,150);e=new aZb;e.i=true;this.b=new W4b(c,e);I2b(this.b._,-150);eNb(this.F,this.b);b=new fGb((wGb(),uGb),qlc(d));eGb(b,(mGb(),kGb));g=new P_b((vlc(),ulc));CGb(WWb(g),b);this.d=new W4b(d,g);I2b(this.d._,150);eNb(this.F,this.d);i=new xUb(75,32,16);a=new fGb(uGb,qlc(i));eGb(a,kGb);f=new P_b(ulc);CGb(WWb(f),a);this.c=new W4b(i,f);I2b(this.c._,-150);eNb(this.F,this.c)};_.ob=function tlc(a){J0b(this.b.cb,0.005);K0b(this.b.cb,0.01);J0b(this.d.cb,0.005);K0b(this.d.cb,0.01);if(this.c){J0b(this.c.cb,0.005);K0b(this.c.cb,0.01)}cFb(this.D.k,this.F,this.a,null,false)};var ulc;NS(1161,1,{},zlc);_.Md=function Alc(){return Ilc(),xlc};_.Nd=function Blc(){return Jlc(),ylc};var xlc,ylc;NS(1162,1,{},Dlc);_.ac=function Elc(){return '#extension GL_OES_standard_derivatives : enable\n\nvarying vec3 vCenter;\n\nfloat edgeFactorTri() {\n\n\tvec3 d = fwidth( vCenter.xyz );\n\tvec3 a3 = smoothstep( vec3( 0.0 ), d * 1.5, vCenter.xyz );\n\treturn min( min( a3.x, a3.y ), a3.z );\n\n}\n\nvoid main() {\n\n\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), edgeFactorTri() );\n\tgl_FragColor.a = 1.0;\n}\n'};NS(1163,1,{},Glc);_.ac=function Hlc(){return 'attribute vec3 center;\nvarying vec3 vCenter;\n\nvoid main() {\n\n\tvCenter = center;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\n}\n'};var TM=Vhb(jLc,'MaterialsWireframe$DemoScene',1160),WM=Vhb(jLc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator',1161),UM=Vhb(jLc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$1',1162),VM=Vhb(jLc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$2',1163);IGc(xi)(19);