function Z0b(){}
function i1b(){}
function h1b(){}
function gRb(a){bRb();hRb.call(this,a,aRb)}
function a1b(){iTb.call(this);this.e=new LEb(10,10,10)}
function Agb(i,a,b,c,d,e,f,g){i.readPixels(a,b,c,d,e,f,g)}
function cSb(a,b){var c,d;b.R&&syb(b);c=b.Q;d=new oDb;SCb(d,b._);dSb(a,b.i,c,d)}
function $0b(a,b){var c,d,e,f;for(d=a.n.Tb();d.xc();){c=ms(d.yc(),143);f=c.gC()==jB?3:4;for(e=0;e<f;++e){c.n.Bc(b)}}}
function SCb(a,b){var c,d,e;c=1/b.c;d=1/b.d;e=1/b.b;a.a[0]=a.a[0]*c;a.a[1]=a.a[1]*c;a.a[2]=a.a[2]*c;a.a[4]=a.a[4]*d;a.a[5]=a.a[5]*d;a.a[6]=a.a[6]*d;a.a[8]=a.a[8]*e;a.a[9]=a.a[9]*e;a.a[10]=a.a[10]*e}
function _0b(a){var b,c,d,e;c=a.A.D.b;Dpb(a.A,a.g,a.z,a.i,false);e=new $wnd.Uint8Array(4);Agb(c,a.c,a.i.d-a.d,1,1,(Nnb(),Mnb).a,(Rhb(),Ohb).a,e);d=e[0]<<16|e[1]<<8|e[2];if(a.f.b>d){b=ms(u9(a.f,d),219);if(!!b.a&&!!b.b&&!!b.c){a.b.W.de(b.a);a.b.Z.de(b.b);a.b._.de(b.c).be(a.e);a.b.db=true}}else{a.b.db=false}}
_=gRb.prototype=$Qb.prototype;_=U0b.prototype;_.pb=function Y0b(){eTb(this.b,new a1b(this.a))};_=a1b.prototype=Z0b.prototype=new hTb;_.gC=function b1b(){return kF};_.md=function c1b(){Mdb(this,new bzb(70,Eeb(this.A.D),1,10000))};_.qc=function d1b(){var a;!!this.z&&dB==dB&&Zyb(this.z,Eeb(this.A.D));a=this.A.D;Vwb(this.i,a.a.width);Uwb(this.i,a.a.height)};_.gb=function e1b(){var a,b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u,v;this.z.W.b=1000;hyb(this.B,this.z);this.a=new xfb(this.z,this.A.D);this.a.s=1;this.a.x=1.2;this.a.o=0.8;this.a.g=true;this.a.e=true;this.a.f=true;this.a.a=0.3;this.g=new QRb;a=this.A.D;this.i=new Ywb(a.a.width,a.a.height);this.i.r=false;hyb(this.B,new ELb(5592405));k=new TLb(1.5);FEb(k.W,0,500,2000);k.M=true;k.y=200;rLb(k,this.z.b);k.c=50;k.v=-2.2E-4;k.A=0.5;k.E=1024;k.C=1024;hyb(this.B,k);g=new Wzb;r=new Wzb;s=new mOb;lOb(s,(WMb(),VMb));d=new aPb;WOb(d,new vzb(16777215));lMb(d,(VNb(),SNb));$Ob(d,VMb);this.f=new A9;for(j=0;j<500;++j){t=new KEb;cEb(t,Math.random()*10000-5000);dEb(t,Math.random()*6000-3000);IEb(t,Math.random()*8000-4000);u=new KEb;cEb(u,Math.random()*2*3.141592653589793);dEb(u,Math.random()*2*3.141592653589793);IEb(u,Math.random()*2*3.141592653589793);v=new KEb;cEb(v,Math.random()*200+100);dEb(v,Math.random()*200+100);IEb(v,Math.random()*200+100);f=new UIb(1,1,1);b=new vzb(ss(Math.random()*16777215));$0b(f,b);c=new gRb(f);c.W.de(t);c.Z.de(u);c._.de(v);cSb(g,c);q=new UIb(1,1,1);o=new vzb(j);$0b(q,o);p=new gRb(q);p.W.de(t);p.Z.de(u);p._.de(v);cSb(r,p);n=new i1b;n.a=t;n.b=u;n.c=v;q9(this.f,n)}e=new hRb(g,d);e.M=true;e.N=true;hyb(this.B,e);hyb(this.g,new hRb(r,s));i=new aPb;WOb(i,new vzb(16776960));this.b=new hRb(new UIb(1,1,1),i);hyb(this.B,this.b);new uDb;this.A.Q=false};_.ld=function f1b(){};_.hb=function g1b(a){vfb(this.a);_0b(this)};_.cM={218:1};_.a=null;_.b=null;_.c=0;_.d=0;_.f=null;_.g=null;_.i=null;_=i1b.prototype=h1b.prototype=new Kb;_.gC=function j1b(){return lF};_.cM={219:1};_.a=null;_.b=null;_.c=null;var kF=O3(plc,'InteractiveCubesGpu$DemoScene'),lF=O3(plc,'InteractiveCubesGpu$Picking');Rhc(Vd)(17);