function Ngc(){}
function Rgc(){}
function Ugc(){}
function p3b(a,b){a.d=b}
function Ggc(a,b){this.b=a;this.c=b}
function Cgc(){F4b.call(this)}
function Jgc(){Jgc=$Cc;Igc=new Ngc}
function Wgc(){Wgc=$Cc;Lgc=new Rgc}
function Xgc(){Xgc=$Cc;Mgc=new Ugc}
var mKc='bottomColor',lKc='topColor';PS(1102,1,zEc);_.Gb=function Agc(){C4b(this.c,new Cgc(this.b))};PS(1103,934,{},Cgc);_.rb=function Dgc(){var b,c,d,e,f,g;this.b=new gMb(40,gDb(this.H.o),1,10000);m1b(this.b.bb,700,180,-500);F3b(this.I,new s3b(16448250,1000,10000));E$b(this.I.c.d,0.6,0.125,1);this.c=new Eub(this.b,this.H.c);q1b(this.c.w,150);b=new wUb(16777215,1.475);m1b(b.bb,100,100,-100);cLb(this.I,b);c=new DUb(16777215,16777215,1.25);E$b(c.L,0.6,0.45,1);E$b(c.b,0.1,0.45,0.95);J0b(c.bb,500);cLb(this.I,c);g=new XZb((Jgc(),Igc));wVb(g,(jXb(),gXb));qEb(lVb(g),lKc,new LIb((cJb(),PIb),new I$b(30719)));qEb(lVb(g),mKc,new LIb(PIb,new I$b(16777215)));qEb(lVb(g),lKc,new LIb(PIb,v$b(c.L)));qEb(lVb(g),nKc,new LIb(QIb,new Ohb(400)));qEb(lVb(g),'exponent',new LIb(QIb,new Ohb(0.6)));p3b(this.I.c,v$b(Cu(Cu(TNb(lVb(g).j,mKc),168).e,230)));f=new zSb(4000,32,15);e=new O2b(f,g);cLb(this.I,e);sDb(this.H.o,this.I.c.d);this.H.o.U=true;this.H.o.V=true;this.H.o.X=true;d=new Vrc;try{Jrc(d,'./static/models/obj/lightmap/lightmap.js',new Ggc(this,d))}catch(a){a=UR(a);if(Fu(a,46)){TKb();SU(SKb,(dsb(),bsb),QJc)}else throw TR(a)}};_.sb=function Egc(a){Cub(this.c);lDb(this.H.o,this.I,this.b,null,false)};PS(1104,1,{},Ggc);_.Hf=function Hgc(){var a;a=new O2b(this.c.b,new $Xb);l1b(a.bb,0);l1b(a.gb,100);cLb(this.b.I,a)};var Igc;PS(1105,1,{},Ngc);_.Rd=function Ogc(){return Wgc(),Lgc};_.Sd=function Pgc(){return Xgc(),Mgc};var Lgc,Mgc;PS(1106,1,{},Rgc);_.ic=function Sgc(){return 'uniform vec3 topColor;\nuniform vec3 bottomColor;\nuniform float offset;\nuniform float exponent;\n\nvarying vec3 worldPosition;\n\nvoid main() {\n\n\tfloat h = normalize( worldPosition + offset ).y;\n\tgl_FragColor = vec4( mix( bottomColor, topColor, max( pow( h, exponent ), 0.0 ) ), 1.0 );\n\n}'};PS(1107,1,{},Ugc);_.ic=function Vgc(){return 'varying vec3 worldPosition;\n\nvoid main() {\n\n\tvec4 mPosition = modelMatrix * vec4( position, 1.0 );\n\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\tworldPosition = mPosition.xyz;\n\n}'};var kM=Chb(nJc,'MaterialsLightmap$DemoScene',1103),jM=Chb(nJc,'MaterialsLightmap$DemoScene$1',1104),nM=Chb(nJc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator',1105),lM=Chb(nJc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator$1',1106),mM=Chb(nJc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator$2',1107);MEc(Di)(20);