function Z9b(){}
function Pac(){}
function Mac(){}
function Uac(){}
function Tac(){}
function Yac(){}
function Xac(){}
function $9b(){H7b.call(this)}
function dac(){dac=gLc;cac=new Pac}
function _ac(){_ac=gLc;Nac=new Uac}
function abc(){abc=gLc;Oac=new Yac}
_=U9b.prototype;_.vb=function Y9b(){D7b(this.b,new $9b(this.a))};_=$9b.prototype=Z9b.prototype=new G7b;_.gC=function _9b(){return vE};_.mb=function aac(){var a,b,c,d,e,f,g,i,j;this.b=new HNb(40,CDb(this.C.n),1,10000);this.b.W.b=300;this.a=new Qpb;Ikb(this.a,_Oc,new sEb((LEb(),HEb),new Qmb));Ikb(this.a,aPc,new sEb(GEb,new Qmb));d=new Qpb;Ikb(d,bPc,new aKb((uKb(),gKb),new xfb(1)));Ikb(d,cOc,new aKb(fKb,new bOb(16777215)));Ikb(d,cPc,new aKb(mKb,new YKb('./static/textures/sprites/spark1.png')));c=new L4b((dac(),cac));YEb(O_b(c),this.a);$Eb(O_b(c),d);T_b(c,(B0b(),u0b));c.L=false;c.Q=true;a=new NOb;for(b=0;b<10000;++b){i=new CTb;WSb(i,Math.random()*2-1);XSb(i,Math.random()*2-1);ATb(i,Math.random()*2-1);i.Ae(200);a.x.Ec(i)}this.c=new S5b(a,c);j=this.c.r.x;g=Qq(Dkb(this.a,_Oc),161).n;f=Qq(Dkb(this.a,aPc),161).n;for(e=0;e<j.Pc();++e){g.Dc(e,new xfb(10));f.Dc(e,new bOb(16755200));Qq(j.Hc(e),193).c<0?XNb(Qq(f.Hc(e),178),0.5+0.1*(e/j.Pc()),0.7,0.9):XNb(Qq(f.Hc(e),178),0.1*(e/j.Pc()),0.9,0.9)}IMb(this.D,this.c)};_.nb=function bac(a){var b,c,d;c=a*0.005;ATb(this.c.Z,0.01*c);for(b=0;b<Qq(Dkb(this.a,_Oc),161).n.Pc();++b){d=Qq(Dkb(this.a,_Oc),161).n;d.Oc(b,new xfb(14+13*Math.sin(0.1*b+c)))}Qq(Dkb(this.a,_Oc),161).i=true;HDb(this.C.n,this.D,this.b,null,false)};_.a=null;_.b=null;_.c=null;var cac;_=Pac.prototype=Mac.prototype=new Jb;_.gC=function Qac(){return EE};_.Md=function Rac(){return _ac(),Nac};_.Nd=function Sac(){return abc(),Oac};var Nac=null,Oac=null;_=Uac.prototype=Tac.prototype=new Jb;_.gC=function Vac(){return CE};_.Yb=function Wac(){return dPc};_=Yac.prototype=Xac.prototype=new Jb;_.gC=function Zac(){return DE};_.Yb=function $ac(){return ePc};var vE=mfb(TOc,'CustomAttributesParticles$DemoScene',XD),EE=mfb(TOc,'CustomAttributesParticles_Resources_default_InlineClientBundleGenerator',Nx),CE=mfb(TOc,'CustomAttributesParticles_Resources_default_InlineClientBundleGenerator$1',Nx),DE=mfb(TOc,'CustomAttributesParticles_Resources_default_InlineClientBundleGenerator$2',Nx);xLc(Wd)(1);