function Yhc(){}
function fic(){}
function eic(){}
function KLb(a,b){a.e=b}
function LLb(a,b){a.k=b}
function I5b(a){C5b();K5b.call(this,a,B5b)}
function Vwb(a,b,c,d,e,f){Wwb(a,b,c,1,1,d.b,e.b,f)}
function Wwb(i,a,b,c,d,e,f,g){i.readPixels(a,b,c,d,e,f,g)}
function _hc(){S7b.call(this);this.g=new OTb(10,10,10)}
function W6b(a,b){var c,d;b.S&&cNb(b);c=b.R;d=new rSb;VRb(d,b.ab);X6b(a,b.s,c,d)}
function Zhc(a,b){var c,d,e,f;for(d=a.n.Zb();d.Dc();){c=ir(d.Ec(),179);f=c.gC()==ZB?3:4;for(e=0;e<f;++e){c.o.Hc(b)}}}
function VRb(a,b){var c,d,e;c=1/b.d;d=1/b.e;e=1/b.c;a.b[0]=a.b[0]*c;a.b[1]=a.b[1]*c;a.b[2]=a.b[2]*c;a.b[4]=a.b[4]*d;a.b[5]=a.b[5]*d;a.b[6]=a.b[6]*d;a.b[8]=a.b[8]*e;a.b[9]=a.b[9]*e;a.b[10]=a.b[10]*e}
function $hc(a){var b,c,d,e;c=a.D.o.M;SDb(a.D.o,a.j,a.b,a.k,false);e=new $wnd.Uint8Array(4);Vwb(c,a.e,a.k.e-a.f,(BAb(),AAb),(VAb(),RAb),e);d=e[0]<<16|e[1]<<8|e[2];if(a.i.c>d){b=ir(Tmb(a.i,d),257);if(!!b.b&&!!b.c&&!!b.d){a.d.X.Be(b.b);a.d.$.Be(b.c);a.d.ab.Be(b.d).ze(a.g);a.d.eb=true}}else{a.d.eb=false}}
_=I5b.prototype=A5b.prototype;_=Thc.prototype;_.zb=function Xhc(){O7b(this.c,new _hc(this.b))};_=_hc.prototype=Yhc.prototype=new R7b;_.gC=function aic(){return rG};_.Jd=function bic(a){LLb(this.k,a.b.p);KLb(this.k,a.b.o)};_.nb=function cic(){var a,b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;Jp((Ivb(),Hvb),(Tvb(),Svb),this);this.b=new SNb(70,NDb(this.D.o),1,10000);this.b.X.c=1000;this.c=new Eub(this.b,this.D.c);this.c.t=1;this.c.y=1.2;this.c.p=0.8;this.c.i=true;this.c.f=true;this.c.g=true;this.c.b=0.3;this.j=new I6b;this.k=new OLb(this.D.o.p,this.D.o.o);this.k.s=false;TMb(this.E,new v$b(5592405));j=new G_b(1.5);ITb(j.X,0,500,2000);j.N=true;j.z=200;J$b(j,this.b.c);j.d=50;j.w=-2.2E-4;j.B=0.5;j.F=1024;j.D=1024;TMb(this.E,j);f=new YOb;q=new YOb;r=new l2b;k2b(r,(V0b(),U0b));c=new e3b;$2b(c,new mOb(16777215));h0b(c,(U1b(),R1b));c3b(c,U0b);this.i=new _mb;for(i=0;i<500;++i){s=new NTb;fTb(s,Math.random()*10000-5000);gTb(s,Math.random()*6000-3000);LTb(s,Math.random()*8000-4000);t=new NTb;fTb(t,Math.random()*2*3.141592653589793);gTb(t,Math.random()*2*3.141592653589793);LTb(t,Math.random()*2*3.141592653589793);u=new NTb;fTb(u,Math.random()*200+100);gTb(u,Math.random()*200+100);LTb(u,Math.random()*200+100);e=new YXb(1,1,1);a=new mOb(qr(Math.random()*16777215));Zhc(e,a);b=new I5b(e);b.X.Be(s);b.$.Be(t);b.ab.Be(u);W6b(f,b);p=new YXb(1,1,1);n=new mOb(i);Zhc(p,n);o=new I5b(p);o.X.Be(s);o.$.Be(t);o.ab.Be(u);W6b(q,o);k=new fic;k.b=s;k.c=t;k.d=u;Pmb(this.i,k)}d=new K5b(f,c);d.N=true;d.O=true;TMb(this.E,d);TMb(this.j,new K5b(q,r));g=new e3b;$2b(g,new mOb(16776960));this.d=new K5b(new YXb(1,1,1),g);TMb(this.E,this.d);new xSb;this.D.o.U=false};_.ob=function dic(a){Cub(this.c);$hc(this);SDb(this.D.o,this.E,this.b,null,false)};_.cM={38:1,131:1,256:1};_.b=null;_.c=null;_.d=null;_.e=0;_.f=0;_.i=null;_.j=null;_.k=null;_=fic.prototype=eic.prototype=new Jb;_.gC=function gic(){return sG};_.cM={257:1};_.b=null;_.c=null;_.d=null;var rG=xfb(hPc,'InteractiveCubesGpu$DemoScene',qE),sG=xfb(hPc,'InteractiveCubesGpu$Picking',gy);ILc(ge)(19);