function $Kb(){}
function QMb(){}
function Okc(){}
function B1b(a,b){a.d=b}
function Pkc(){j7b.call(this)}
function mLb(){iKb();fLb.call(this,256,256)}
function awb(a,b,c,d,e){bwb(a,36160,b.b,c.b+d,e,0)}
function swb(a,b,c,d,e,f,g){twb(a,b.b+c,0,f.b,d,e,0,f.b,g.b,null)}
function lLb(a,b,c,d,e){b.bindFramebuffer(36160,c);awb(b,(Azb(),wzb),d,e,a.A)}
function RMb(a,b,c){var d,e;e=a.i;d=e.s;e.s=false;e.b=0;jDb(b,c,a.e,e,false);e.b=1;jDb(b,c,a.b,e,false);e.b=2;jDb(b,c,a.f,e,false);e.b=3;jDb(b,c,a.c,e,false);e.b=4;jDb(b,c,a.g,e,false);e.s=d;e.b=5;jDb(b,c,a.d,e,false)}
function SMb(){jMb();xMb.call(this);this.e=new jNb(90,1,1,1000);_Sb(this.e.bb,0,-1,0);LMb(this.e,new fTb(1,0,0));kMb(this,this.e);this.b=new jNb(90,1,1,1000);_Sb(this.b.bb,0,-1,0);LMb(this.b,new fTb(-1,0,0));kMb(this,this.b);this.f=new jNb(90,1,1,1000);_Sb(this.f.bb,0,0,1);LMb(this.f,new fTb(0,1,0));kMb(this,this.f);this.c=new jNb(90,1,1,1000);_Sb(this.c.bb,0,0,-1);LMb(this.c,new fTb(0,-1,0));kMb(this,this.c);this.g=new jNb(90,1,1,1000);_Sb(this.g.bb,0,-1,0);LMb(this.g,new fTb(0,0,1));kMb(this,this.g);this.d=new jNb(90,1,1,1000);_Sb(this.d.bb,0,-1,0);LMb(this.d,new fTb(0,0,-1));kMb(this,this.d);this.i=new mLb;nKb(this.i,(Uzb(),Szb));pKb(this.i,(VAb(),TAb));rKb(this.i,(fBb(),_Ab))}
_=mLb.prototype=$Kb.prototype=new _Kb;_.gC=function nLb(){return gB};_.Od=function oLb(){return Oq(kmb(this.c,this.b))};_.Pd=function pLb(a){var b,c;if(this.c)return;wKb(this,a.createTexture());c=XQb(this.k)&&XQb(this.e);this.c=new smb;this.d=new smb;vvb(a,(HBb(),ABb),this.A);uKb(this,a,0,ABb,c);for(b=0;b<6;++b){gmb(this.c,a.createFramebuffer());gmb(this.d,a.createRenderbuffer());swb(a,EBb,b,this.k,this.e,this.p,this.z);lLb(this,a,Oq(kmb(this.c,b)),EBb,b);eLb(this,a,Oq(kmb(this.d,b)))}c&&dwb(a,ABb.b);vvb(a,ABb,null);a.bindRenderbuffer(36161,null);a.bindFramebuffer(36160,null)};_.Qd=function qLb(a){vvb(a,(HBb(),ABb),this.A);dwb(a,ABb.b);vvb(a,ABb,null)};_.cM={171:1,172:1};_.b=0;_.c=null;_.d=null;_=SMb.prototype=QMb.prototype=new hMb;_.gC=function TMb(){return qB};_.cM={236:1,242:1};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_=Jkc.prototype;_.wb=function Nkc(){f7b(this.c,new Pkc(this.b))};_=Pkc.prototype=Okc.prototype=new i7b;_.gC=function Qkc(){return BG};_.nb=function Rkc(){var a,b,c,d;this.b=new jNb(this.e,eDb(this.D.o),1,1000);this.b.X.c=400;d=new AKb('./static/textures/ruins.jpg');b=new E1b;b.k=d;c=new b5b(new fYb(500,60,40),b);c.ab.d=-1;kMb(this.E,c);this.d=new SMb;rKb(this.d.i,(fBb(),aBb));kMb(this.E,this.d);a=new E1b;B1b(a,this.d.i);this.o=new b5b(new fYb(20,60,40),a);kMb(this.E,this.o);this.c=new b5b(new pXb(20,20,20),a);kMb(this.E,this.c);this.q=new b5b(new vYb(20,5,100,100),a);kMb(this.E,this.q);jDb(this.D.o,this.E,this.b,null,false)};_.ob=function Skc(a){this.g+=0.15;this.f=fgb(-85,hgb(85,this.f));this.n=(90-this.f)*3.141592653589793/180;this.p=this.g*3.141592653589793/180;ySb(this.o.X,Math.sin(a*0.001)*30);zSb(this.o.X,Math.sin(a*0.0011)*30);cTb(this.o.X,Math.sin(a*0.0012)*30);this.o.$.d+=0.02;this.o.$.e+=0.03;ySb(this.c.X,Math.sin(a*0.001+2)*30);zSb(this.c.X,Math.sin(a*0.0011+2)*30);cTb(this.c.X,Math.sin(a*0.0012+2)*30);this.c.$.d+=0.02;this.c.$.e+=0.03;ySb(this.q.X,Math.sin(a*0.001+4)*30);zSb(this.q.X,Math.sin(a*0.0011+4)*30);cTb(this.q.X,Math.sin(a*0.0012+4)*30);this.q.$.d+=0.02;this.q.$.e+=0.03;ySb(this.b.X,100*lgb(this.n)*dgb(this.p));zSb(this.b.X,100*dgb(this.n));cTb(this.b.X,100*lgb(this.n)*lgb(this.p));LMb(this.b,this.E.X);this.o.eb=false;RMb(this.d,this.D.o,this.E);this.o.eb=true;jDb(this.D.o,this.E,this.b,null,false)};_.cM={264:1};_.b=null;_.c=null;_.d=null;_.e=70;_.f=0;_.g=0;_.i=false;_.j=0;_.k=0;_.n=0;_.o=null;_.p=0;_.q=null;var qB=Qeb(CPc,'CubeCamera',FD),BG=Qeb(uOc,'MaterialsCubemapDynamicReflection$DemoScene',RD);_Kc(Wd)(27);