function Hoc(){}
function Loc(){}
function Ooc(){}
function pIb(a,b){a.f=b}
function zoc(){eac.call(this)}
function Doc(){Doc=kNc;Coc=new Hoc}
function Qoc(){Qoc=kNc;Foc=new Loc}
function Roc(){Roc=kNc;Goc=new Ooc}
function NIb(a,b){!a.b&&(a.b=new sSb);a.b.vd(MSc,b)}
function yoc(a){var b,c;c=new _qb;for(b=0;b<a.j.Xc();b++){Wu(a.j.Pc(b),241);Qqb(c,b,new xrb(Mu(DT,OOc,299,[new B6b(1,0,0),new B6b(0,1,0),new B6b(0,0,1)])))}return c}
JU(1174,1,XOc);_.Db=function woc(){G9b(this.c,new zoc(this.b))};JU(1175,973,{},zoc);_.ob=function Aoc(){var a,b,c,d,e,f,g,i;this.b=new NQb(40,bHb(this.H.n),1,2000);x6b(this.b.ab,800);c=new vWb(150,150,150);d=new vWb(150,150,150);e=new R_b;e.j=true;this.c=new Z7b(c,e);K5b(this.c.ab,-150);KPb(this.I,this.c);b=new qIb((HIb(),FIb),yoc(d));pIb(b,(xIb(),vIb));g=new R2b((Doc(),Coc));NIb(KZb(g),b);this.e=new Z7b(d,g);K5b(this.e.ab,150);KPb(this.I,this.e);i=new kXb(75,32,16);a=new qIb(FIb,yoc(i));pIb(a,vIb);f=new R2b(Coc);NIb(KZb(f),a);this.d=new Z7b(i,f);K5b(this.d.ab,-150);KPb(this.I,this.d)};_.pb=function Boc(a){L3b(this.c.db,0.005);M3b(this.c.db,0.01);L3b(this.e.db,0.005);M3b(this.e.db,0.01);if(this.d){L3b(this.d.db,0.005);M3b(this.d.db,0.01)}nHb(this.H.n,this.I,this.b,null,false)};var Coc;JU(1176,1,{},Hoc);_.Vd=function Ioc(){return Qoc(),Foc};_.Wd=function Joc(){return Roc(),Goc};var Foc,Goc;JU(1177,1,{},Loc);_.uc=function Moc(){return '#extension GL_OES_standard_derivatives : enable\n\nvarying vec3 vCenter;\n\nfloat edgeFactorTri() {\n\n\tvec3 d = fwidth( vCenter.xyz );\n\tvec3 a3 = smoothstep( vec3( 0.0 ), d * 1.5, vCenter.xyz );\n\treturn min( min( a3.x, a3.y ), a3.z );\n\n}\n\nvoid main() {\n\n\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), edgeFactorTri() );\n\tgl_FragColor.a = 1.0;\n}\n'};JU(1178,1,{},Ooc);_.uc=function Poc(){return 'attribute vec3 center;\nvarying vec3 vCenter;\n\nvoid main() {\n\n\tvCenter = center;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\n}\n'};var NN=_jb(XTc,'MaterialsWireframe$DemoScene',1175),QN=_jb(XTc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator',1176),ON=_jb(XTc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$1',1177),PN=_jb(XTc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$2',1178);jPc(Ii)(19);