function ojc(){}
function sjc(){}
function vjc(){}
function mEb(a,b){a.f=b}
function gjc(){$4b.call(this)}
function xjc(){xjc=tDc;mjc=new sjc}
function kjc(){kjc=tDc;jjc=new ojc}
function yjc(){yjc=tDc;njc=new vjc}
function KEb(a,b){!a.b&&(a.b=new rOb);a.b.zd(GIc,b)}
function fjc(a){var b,c,d;d=new Vob;for(b=0;b<a.o._c();b++){c=Uu(a.o.Tc(b),180);c.cZ==jH?Kob(d,b,new tpb(Ku(dS,MEc,237,[new z2b(1,0,0,0),new z2b(0,1,0,0),new z2b(0,0,1,0)]))):Kob(d,b,new tpb(Ku(dS,MEc,237,[new z2b(1,0,0,1),new z2b(1,1,0,1),new z2b(0,1,0,1),new z2b(0,0,0,1)])))}return d}
function j4b(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u,v,w,A,B,C,D,F,G,H,I,J;k=new Vob;i=new Vob;j=new Vob;for(o=0,r=a.k.c;o<r;o++){Lob(i,new Vob)}for(p=0,s=a.n.c;p<s;p++){Lob(j,new Vob)}for(n=0,q=a.o._c();n<q;n++){f=Uu(a.o.Tc(n),180);if(f.cZ==kH){b=f.e;c=f.f;d=f.g;e=Uu(f,181).b;A=new WNb(0,0,0);B=new WNb(0,0,0);S$b(A.j,f.j);S$b(B.j,f.j);RNb(A,f.k);RNb(B,f.k);A.e=b;A.f=c;A.g=e;B.e=c;B.f=d;B.g=e;if(f.o._c()==4){A.o.$c(0,Q$b(Uu(f.o.Tc(0),230)));A.o.$c(1,Q$b(Uu(f.o.Tc(1),230)));A.o.$c(2,Q$b(Uu(f.o.Tc(3),230)));B.o.$c(0,Q$b(Uu(f.o.Tc(1),230)));B.o.$c(1,Q$b(Uu(f.o.Tc(2),230)));B.o.$c(2,Q$b(Uu(f.o.Tc(3),230)))}Lu(k.b,k.c++,A);Lu(k.b,k.c++,B);for(t=0,v=a.n.c;t<v;t++){if(Uu(Oob(a.n,t),120)._c()>0){H=Uu(Uu(Oob(a.n,t),120).Tc(n),120);C=Uu(H.Tc(0),234);D=Uu(H.Tc(1),234);F=Uu(H.Tc(2),234);G=Uu(H.Tc(3),234);I=new tpb(Ku(bS,MEc,234,[C.kf(),D.kf(),G.kf()]));J=new tpb(Ku(bS,MEc,234,[D.kf(),F.kf(),G.kf()]));(Jeb(t,j.c),Uu(j.b[t],120)).Qc(I);(Jeb(t,j.c),Uu(j.b[t],120)).Qc(J)}}for(u=0,w=a.k.c;u<w;u++){if(Uu(Oob(a.k,u),120)._c()>0){g=Uu(Uu(Oob(a.k,u),120).Tc(n),234);(Jeb(u,i.c),Uu(i.b[u],120)).Qc(g);(Jeb(u,i.c),Uu(i.b[u],120)).Qc(g)}}}else{Lu(k.b,k.c++,f);for(u=0,w=a.k.c;u<w;u++){(Jeb(u,i.c),Uu(i.b[u],120)).Qc(Uu(Uu(Oob(a.k,u),120).Tc(n),234))}for(t=0,v=a.n.c;t<v;t++){(Jeb(t,j.c),Uu(j.b[t],120)).Qc(Uu(Uu(Oob(a.n,t),120).Tc(n),120))}}}a.o=k;a.k=i;a.n=j;bNb(a);cNb(a,khb());fNb(a);a.V.b&&eNb(a)}
kT(1138,1,UEc);_.Gb=function djc(){X4b(this.c,new gjc(this.b))};kT(1139,940,{},gjc);_.rb=function hjc(){var a,b,c,d,e,f,g,i,j,k,n;this.b=new BMb(40,BDb(this.H.o),1,2000);L1b(this.b.bb,800);d=new mSb(150,150,150);e=new mSb(150,150,150);f=new mSb(150,150,150);j4b(f);g=new NXb;g.i=true;this.c=new h3b(d,g);b1b(this.c.bb,0);xLb(this.I,this.c);b=new nEb((EEb(),DEb),fjc(e));mEb(b,(uEb(),sEb));j=new q$b((kjc(),jjc));KEb(GVb(j),b);this.e=new h3b(e,j);b1b(this.e.bb,300);xLb(this.I,this.e);c=new nEb(DEb,fjc(f));mEb(c,sEb);k=new q$b(jjc);KEb(GVb(k),c);this.f=new h3b(f,k);b1b(this.f.bb,-300);xLb(this.I,this.f);n=new USb(75,32,16);a=new nEb(DEb,fjc(n));mEb(a,sEb);i=new q$b(jjc);KEb(GVb(i),a);this.d=new h3b(n,i);b1b(this.d.bb,0);xLb(this.I,this.d)};_.sb=function ijc(a){Y0b(this.c.eb,0.005);Z0b(this.c.eb,0.01);Y0b(this.e.eb,0.005);Z0b(this.e.eb,0.01);Y0b(this.f.eb,0.005);Z0b(this.f.eb,0.01);if(this.d){Y0b(this.d.eb,0.005);Z0b(this.d.eb,0.01)}GDb(this.H.o,this.I,this.b,null,false)};var jjc;kT(1140,1,{},ojc);_.Vd=function pjc(){return xjc(),mjc};_.Wd=function qjc(){return yjc(),njc};var mjc,njc;kT(1141,1,{},sjc);_.mc=function tjc(){return '#extension GL_OES_standard_derivatives : enable\n\nvarying vec4 vCenter;\n\nfloat edgeFactorTri() {\n\n\tvec3 d = fwidth( vCenter.xyz );\n\tvec3 a3 = smoothstep( vec3( 0.0 ), d * 1.5, vCenter.xyz );\n\treturn min( min( a3.x, a3.y ), a3.z );\n\n}\n\nfloat edgeFactorQuad1() {\n\n\tvec2 d = fwidth( vCenter.xy );\n\tvec2 a2 = smoothstep( vec2( 0.0 ), d * 1.5, vCenter.xy );\n\n\treturn min( a2.x, a2.y );\n\n}\n\nfloat edgeFactorQuad2() {\n\n\tvec2 d = fwidth( 1.0 - vCenter.xy );\n\tvec2 a2 = smoothstep( vec2( 0.0 ), d * 1.5, 1.0 - vCenter.xy );\n\n\treturn min( a2.x, a2.y );\n}\n\nvoid main() {\n\n\tif ( vCenter.w == 0.0 ) {\n\n\t\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), edgeFactorTri() );\n\n\t} else {\n\n\t\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), min( edgeFactorQuad1(), edgeFactorQuad2() ) );\n\n\t}\n\n\tgl_FragColor.a = 1.0;\n\n}\n'};kT(1142,1,{},vjc);_.mc=function wjc(){return 'attribute vec4 center;\nvarying vec4 vCenter;\n\nvoid main() {\n\n\tvCenter = center;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\n}\n'};var hN=Whb(NJc,'MaterialsWireframe$DemoScene',1139),dS=Vhb(OKc,'Vector4;',1439,qJ),kN=Whb(NJc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator',1140),iN=Whb(NJc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$1',1141),jN=Whb(NJc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$2',1142);fFc(Ei)(21);