function Occ(){}
function Tcc(){}
function Xcc(){}
function _cc(){}
function Ucc(a){this.a=a}
function Ycc(a){this.a=a}
function adc(a){this.a=a}
function sNb(a,b){a.b=b}
function ENb(a,b){a.b=b}
function FNb(a,b){a.c=b}
function Pcc(){H7b.call(this)}
function xNb(a){SRb(a.q,a.c,a.e,a.f,a.a,a.d,a.b)}
_=Jcc.prototype;_.vb=function Ncc(){D7b(this.b,new Pcc(this.a))};_=Pcc.prototype=Occ.prototype=new G7b;_.gC=function Qcc(){return _E};_.mb=function Rcc(){var a,b,c,d,e,f,g,i,j,k;this.c=new HNb(50,0.5*CDb(this.C.n),1,10000);this.c.W.b=2500;gNb(new Ucc(this));this.f=new HNb(50,CDb(this.C.n)*0.5,150,1000);gNb(new Ycc(this));this.d=new yNb(0.5*this.C.n.o,this.C.n.n,150,1000);gNb(new adc(this));this.g=new a$b(this.f);IMb(this.D,this.g);this.e=new a$b(this.d);IMb(this.D,this.e);this.a=this.f;this.b=this.g;this.d.Z.d=3.141592653589793;this.f.Z.d=3.141592653589793;this.i=new VMb;IMb(this.i,this.f);IMb(this.i,this.d);IMb(this.D,this.i);a=new a2b;X1b(a,new bOb(16777215));a.g=true;this.j=new z5b(new DYb(100,16,8),a);IMb(this.D,this.j);b=new a2b;X1b(b,new bOb(65280));b.g=true;f=new z5b(new DYb(50,16,8),b);f.W.d=150;IMb(this.j,f);c=new a2b;X1b(c,new bOb(255));g=new z5b(new DYb(5,16,8),c);g.W.b=150;IMb(this.i,g);d=new NOb;for(e=0;e<10000;++e){k=new CTb;WSb(k,2000*(0.5-Math.random()));XSb(k,2000*(0.5-Math.random()));ATb(k,2000*(0.5-Math.random()));d.x.Ec(k)}j=new t4b;r4b(j,new bOb(8947848));i=new S5b(d,j);IMb(this.D,i);this.C.n.N=false};_.nb=function Scc(a){var b;b=a*5.0E-4;WSb(this.j.W,700*Math.cos(b));ATb(this.j.W,700*Math.sin(b));XSb(this.j.W,700*Math.sin(b));WSb(Qq(Imb(this.j.K,0),236).Wd(),70*Math.cos(2*b));ATb(Qq(Imb(this.j.K,0),236).Wd(),70*Math.sin(b));if(this.a==this.f){FNb(this.f,35+30*Math.sin(0.5*b));ENb(this.f,this.j.W.ne());GNb(this.f);_Zb(this.g);this.g.db=true;this.e.db=false}else{sNb(this.d,this.j.W.ne());xNb(this.d);_Zb(this.e);this.e.db=true;this.g.db=false}this.i.Zd(this.j.W);zDb(this.C.n);this.b.db=false;aEb(this.C.n,0,~~(this.C.n.o/2),this.C.n.n);HDb(this.C.n,this.D,this.a,null,false);this.b.db=true;aEb(this.C.n,~~(this.C.n.o/2),~~(this.C.n.o/2),this.C.n.n);HDb(this.C.n,this.D,this.c,null,false)};_.cM={248:1};_.a=null;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;_=Ucc.prototype=Tcc.prototype=new Jb;_.gC=function Vcc(){return YE};_.Gd=function Wcc(a){DNb(this.a.c,0.5*CDb(a.a))};_.cM={38:1,131:1};_.a=null;_=Ycc.prototype=Xcc.prototype=new Jb;_.gC=function Zcc(){return ZE};_.Gd=function $cc(a){DNb(this.a.f,0.5*CDb(a.a))};_.cM={38:1,131:1};_.a=null;_=adc.prototype=_cc.prototype=new Jb;_.gC=function bdc(){return $E};_.Gd=function cdc(a){vNb(this.a.d,0.5*a.a.o,a.a.n)};_.cM={38:1,131:1};_.a=null;var _E=mfb(VOc,'Cameras$DemoScene',XD),YE=mfb(VOc,'Cameras$DemoScene$1',Nx),ZE=mfb(VOc,'Cameras$DemoScene$2',Nx),$E=mfb(VOc,'Cameras$DemoScene$3',Nx);xLc(Wd)(8);