function Cnc(){}
function Gnc(){}
function Jnc(){}
function PHb(a,b){a.e=b}
function unc(){F9b.call(this)}
function ync(){ync=dKc;xnc=new Cnc}
function Lnc(){Lnc=dKc;Anc=new Gnc}
function Mnc(){Mnc=dKc;Bnc=new Jnc}
function lIb(a,b){!a.a&&(a.a=new SRb);a.a.od(DPc,b)}
function tnc(a){var b,c;c=new zqb;for(b=0;b<a.i.Qc();b++){Bu(a.i.Ic(b),241);oqb(c,b,new Xqb(ru(bT,FLc,299,[new _5b(1,0,0),new _5b(0,1,0),new _5b(0,0,1)])))}return c}
hU(1173,1,OLc);_.zb=function rnc(){f9b(this.b,new unc(this.a))};hU(1174,971,{},unc);_.nb=function vnc(){var a,b,c,d,e,f,g,i;this.a=new lQb(40,BGb(this.G.k),1,2000);X5b(this.a._,800);c=new VVb(150,150,150);d=new VVb(150,150,150);e=new p_b;e.i=true;this.b=new x7b(c,e);i5b(this.b._,-150);iPb(this.H,this.b);b=new QHb((fIb(),dIb),tnc(d));PHb(b,(XHb(),VHb));g=new p2b((ync(),xnc));lIb(iZb(g),b);this.d=new x7b(d,g);i5b(this.d._,150);iPb(this.H,this.d);i=new KWb(75,32,16);a=new QHb(dIb,tnc(i));PHb(a,VHb);f=new p2b(xnc);lIb(iZb(f),a);this.c=new x7b(i,f);i5b(this.c._,-150);iPb(this.H,this.c)};_.ob=function wnc(a){j3b(this.b.cb,0.005);k3b(this.b.cb,0.01);j3b(this.d.cb,0.005);k3b(this.d.cb,0.01);if(this.c){j3b(this.c.cb,0.005);k3b(this.c.cb,0.01)}NGb(this.G.k,this.H,this.a,null,false)};var xnc;hU(1175,1,{},Cnc);_.Od=function Dnc(){return Lnc(),Anc};_.Pd=function Enc(){return Mnc(),Bnc};var Anc,Bnc;hU(1176,1,{},Gnc);_.nc=function Hnc(){return '#extension GL_OES_standard_derivatives : enable\n\nvarying vec3 vCenter;\n\nfloat edgeFactorTri() {\n\n\tvec3 d = fwidth( vCenter.xyz );\n\tvec3 a3 = smoothstep( vec3( 0.0 ), d * 1.5, vCenter.xyz );\n\treturn min( min( a3.x, a3.y ), a3.z );\n\n}\n\nvoid main() {\n\n\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), edgeFactorTri() );\n\tgl_FragColor.a = 1.0;\n}\n'};hU(1177,1,{},Jnc);_.nc=function Knc(){return 'attribute vec3 center;\nvarying vec3 vCenter;\n\nvoid main() {\n\n\tvCenter = center;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\n}\n'};var lN=Ajb(PQc,'MaterialsWireframe$DemoScene',1174),oN=Ajb(PQc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator',1175),mN=Ajb(PQc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$1',1176),nN=Ajb(PQc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$2',1177);aMc(xi)(19);