function $mc(){}
function cnc(){}
function fnc(){}
function PGb(a,b){a.e=b}
function Smc(){X7b.call(this)}
function Wmc(){Wmc=ZGc;Vmc=new $mc}
function hnc(){hnc=ZGc;Ymc=new cnc}
function inc(){inc=ZGc;Zmc=new fnc}
function lHb(a,b){!a.a&&(a.a=new qQb);a.a.nd(nMc,b)}
function Rmc(a){var b,c;c=new Cpb;for(b=0;b<a.i.Pc();b++){su(a.i.Hc(b),240);rpb(c,b,new $pb(iu(_R,yIc,299,[new t4b(1,0,0),new t4b(0,1,0),new t4b(0,0,1)])))}return c}
fT(1176,1,HIc);_.zb=function Pmc(){x7b(this.b,new Smc(this.a))};fT(1177,967,{},Smc);_.nb=function Tmc(){var a,b,c,d,e,f,g,i;this.a=new POb(40,BFb(this.D.k),1,2000);p4b(this.a._,800);c=new rUb(150,150,150);d=new rUb(150,150,150);e=new LZb;e.i=true;this.b=new R5b(c,e);D3b(this.b._,-150);PNb(this.F,this.b);b=new QGb((fHb(),dHb),Rmc(d));PGb(b,(XGb(),VGb));g=new K0b((Wmc(),Vmc));lHb(FXb(g),b);this.d=new R5b(d,g);D3b(this.d._,150);PNb(this.F,this.d);i=new gVb(75,32,16);a=new QGb(dHb,Rmc(i));PGb(a,VGb);f=new K0b(Vmc);lHb(FXb(f),a);this.c=new R5b(i,f);D3b(this.c._,-150);PNb(this.F,this.c)};_.ob=function Umc(a){E1b(this.b.cb,0.005);F1b(this.b.cb,0.01);E1b(this.d.cb,0.005);F1b(this.d.cb,0.01);if(this.c){E1b(this.c.cb,0.005);F1b(this.c.cb,0.01)}NFb(this.D.k,this.F,this.a,null,false)};var Vmc;fT(1178,1,{},$mc);_.Md=function _mc(){return hnc(),Ymc};_.Nd=function anc(){return inc(),Zmc};var Ymc,Zmc;fT(1179,1,{},cnc);_.mc=function dnc(){return '#extension GL_OES_standard_derivatives : enable\n\nvarying vec3 vCenter;\n\nfloat edgeFactorTri() {\n\n\tvec3 d = fwidth( vCenter.xyz );\n\tvec3 a3 = smoothstep( vec3( 0.0 ), d * 1.5, vCenter.xyz );\n\treturn min( min( a3.x, a3.y ), a3.z );\n\n}\n\nvoid main() {\n\n\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), edgeFactorTri() );\n\tgl_FragColor.a = 1.0;\n}\n'};fT(1180,1,{},fnc);_.mc=function gnc(){return 'attribute vec3 center;\nvarying vec3 vCenter;\n\nvoid main() {\n\n\tvCenter = center;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\n}\n'};var hN=Dib(yNc,'MaterialsWireframe$DemoScene',1177),kN=Dib(yNc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator',1178),iN=Dib(yNc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$1',1179),jN=Dib(yNc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$2',1180);UIc(xi)(20);