function lwb(){}
function kwb(){}
function Qxb(){}
function C$b(){}
function _Jb(a,b){a.d=b}
function D$b(){NPb.call(this)}
function swb(){owb.call(this,(Zmb(),Wmb),Wmb,(Emb(),Cmb),(Qmb(),Lmb),(wmb(),vmb),(Agb(),xgb))}
function owb(a,b,c,d,e,f){bwb.call(this);this.f=256;this.e=256;this.u=a;this.v=b;this.n=c;this.p=d;this.g=e;this.s=f}
function Rxb(a,b,c){var d,e;e=a.i;d=e.j;e.j=false;e.b=0;Qnb(b,c,a.e,e);e.b=1;Qnb(b,c,a.b,e);e.b=2;Qnb(b,c,a.f,e);e.b=3;Qnb(b,c,a.c,e);e.b=4;Qnb(b,c,a.g,e);e.j=d;e.b=5;Qnb(b,c,a.d,e)}
function Sxb(){Cxb.call(this);this.e=new gyb(90,1,1,1000);kCb(this.e.K,0,-1,0);Mxb(this.e,new pCb(1,0,0));sxb(this,this.e);this.b=new gyb(90,1,1,1000);kCb(this.b.K,0,-1,0);Mxb(this.b,new pCb(-1,0,0));sxb(this,this.b);this.f=new gyb(90,1,1,1000);kCb(this.f.K,0,0,1);Mxb(this.f,new pCb(0,1,0));sxb(this,this.f);this.c=new gyb(90,1,1,1000);kCb(this.c.K,0,0,-1);Mxb(this.c,new pCb(0,-1,0));sxb(this,this.c);this.g=new gyb(90,1,1,1000);kCb(this.g.K,0,-1,0);Mxb(this.g,new pCb(0,0,1));sxb(this,this.g);this.d=new gyb(90,1,1,1000);kCb(this.d.K,0,-1,0);Mxb(this.d,new pCb(0,0,-1));sxb(this,this.d);this.i=new swb;Tvb(this.i,(wmb(),umb));Vvb(this.i,(Emb(),Cmb));Wvb(this.i,(Qmb(),Kmb))}
_=lwb.prototype=new Qvb;_.gC=function pwb(){return Hz};_.e=0;_.f=0;_=swb.prototype=kwb.prototype=new lwb;_.gC=function twb(){return Gz};_.cM={141:1};_.b=0;_.c=null;_.d=null;_=Sxb.prototype=Qxb.prototype=new qxb;_.gC=function Txb(){return Rz};_.cM={194:1,202:1};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_=x$b.prototype;_.rb=function B$b(){JPb(this.c,new D$b(this.b))};_=D$b.prototype=C$b.prototype=new MPb;_.gC=function E$b(){return aE};_.pd=function F$b(){xcb(this,new gyb(this.d,pdb(this.B.D),1,1000))};_.ib=function G$b(){var a,b,c,d;this.A.E.c=400;sxb(this.C,this.A);d=(MOb(),OOb('./static/textures/ruins.jpg',(Bwb(),Awb),null));b=new cKb;b.k=d;c=new nNb(new xHb(500,60,40),b);c.J.d=-1;sxb(this.C,c);this.c=new Sxb;Wvb(this.c.i,(Qmb(),Lmb));sxb(this.C,this.c);a=new cKb;_Jb(a,this.c.i);this.n=new nNb(new xHb(20,60,40),a);sxb(this.C,this.n);this.b=new nNb(new LGb(20,20,20),a);sxb(this.C,this.b);this.p=new nNb(new LHb(20,5,100,100),a);sxb(this.C,this.p)};_.od=function H$b(){};_.jb=function I$b(a){this.f+=0.15;this.e=w3(-85,y3(85,this.e));this.k=(90-this.e)*3.141592653589793/180;this.o=this.f*3.141592653589793/180;IBb(this.n.E,Math.sin(a*0.001)*30);JBb(this.n.E,Math.sin(a*0.0011)*30);mCb(this.n.E,Math.sin(a*0.0012)*30);this.n.H.d+=0.02;this.n.H.e+=0.03;IBb(this.b.E,Math.sin(a*0.001+2)*30);JBb(this.b.E,Math.sin(a*0.0011+2)*30);mCb(this.b.E,Math.sin(a*0.0012+2)*30);this.b.H.d+=0.02;this.b.H.e+=0.03;IBb(this.p.E,Math.sin(a*0.001+4)*30);JBb(this.p.E,Math.sin(a*0.0011+4)*30);mCb(this.p.E,Math.sin(a*0.0012+4)*30);this.p.H.d+=0.02;this.p.H.e+=0.03;IBb(this.A.E,100*C3(this.k)*u3(this.o));JBb(this.A.E,100*u3(this.k));mCb(this.A.E,100*C3(this.k)*C3(this.o));Mxb(this.A,new pCb(0,0,0));this.n.N=false;Rxb(this.c,this.B,this.C);this.n.N=true};_.cM={220:1};_.b=null;_.c=null;_.d=70;_.e=0;_.f=0;_.g=false;_.i=0;_.j=0;_.k=0;_.n=null;_.o=0;_.p=null;var Hz=m2(Jac,'RenderTargetTexture'),Rz=m2(Kac,'CubeCamera'),aE=m2(k9b,'MaterialsCubemapDynamicReflection$DemoScene');R5b(be)(20);