function koc(){}
function ooc(){}
function roc(){}
function SHb(a,b){a.e=b}
function coc(){H9b.call(this)}
function goc(){goc=PMc;foc=new koc}
function toc(){toc=PMc;ioc=new ooc}
function uoc(){uoc=PMc;joc=new roc}
function oIb(a,b){!a.a&&(a.a=new VRb);a.a.od(fSc,b)}
function boc(a){var b,c;c=new Cqb;for(b=0;b<a.i.Qc();b++){su(a.i.Ic(b),241);rqb(c,b,new $qb(iu(XS,pOc,299,[new c6b(1,0,0),new c6b(0,1,0),new c6b(0,0,1)])))}return c}
bU(1176,1,yOc);_.zb=function _nc(){h9b(this.b,new coc(this.a))};bU(1177,974,{},coc);_.nb=function doc(){var a,b,c,d,e,f,g,i;this.a=new oQb(40,EGb(this.G.k),1,2000);$5b(this.a._,800);c=new YVb(150,150,150);d=new YVb(150,150,150);e=new s_b;e.i=true;this.b=new A7b(c,e);l5b(this.b._,-150);lPb(this.H,this.b);b=new THb((iIb(),gIb),boc(d));SHb(b,($Hb(),YHb));g=new s2b((goc(),foc));oIb(lZb(g),b);this.d=new A7b(d,g);l5b(this.d._,150);lPb(this.H,this.d);i=new NWb(75,32,16);a=new THb(gIb,boc(i));SHb(a,YHb);f=new s2b(foc);oIb(lZb(f),a);this.c=new A7b(i,f);l5b(this.c._,-150);lPb(this.H,this.c)};_.ob=function eoc(a){m3b(this.b.cb,0.005);n3b(this.b.cb,0.01);m3b(this.d.cb,0.005);n3b(this.d.cb,0.01);if(this.c){m3b(this.c.cb,0.005);n3b(this.c.cb,0.01)}QGb(this.G.k,this.H,this.a,null,false)};var foc;bU(1178,1,{},koc);_.Od=function loc(){return toc(),ioc};_.Pd=function moc(){return uoc(),joc};var ioc,joc;bU(1179,1,{},ooc);_.nc=function poc(){return '#extension GL_OES_standard_derivatives : enable\n\nvarying vec3 vCenter;\n\nfloat edgeFactorTri() {\n\n\tvec3 d = fwidth( vCenter.xyz );\n\tvec3 a3 = smoothstep( vec3( 0.0 ), d * 1.5, vCenter.xyz );\n\treturn min( min( a3.x, a3.y ), a3.z );\n\n}\n\nvoid main() {\n\n\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), edgeFactorTri() );\n\tgl_FragColor.a = 1.0;\n}\n'};bU(1180,1,{},roc);_.nc=function soc(){return 'attribute vec3 center;\nvarying vec3 vCenter;\n\nvoid main() {\n\n\tvCenter = center;\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\n}\n'};var fN=Djb(qTc,'MaterialsWireframe$DemoScene',1177),iN=Djb(qTc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator',1178),gN=Djb(qTc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$1',1179),hN=Djb(qTc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$2',1180);MOc(xi)(19);