function Kgc(){}
function Ogc(){}
function Rgc(){}
function l4b(a,b){a.c=b}
function Dgc(a,b){this.a=a;this.b=b}
function zgc(){y5b.call(this)}
function uYb(a){VVb.call(this);this.a=a}
function Ggc(){Ggc=Azc;Fgc=new Kgc}
function Tgc(){Tgc=Azc;Igc=new Ogc}
function Ugc(){Ugc=Azc;Jgc=new Rgc}
var gHc='bottomColor',fHc='topColor';cS(899,892,{229:1,236:1},uYb);_.Me=function wYb(){return null};cS(1099,1,eBc);_.yb=function xgc(){v5b(this.b,new zgc(this.a))};cS(1100,943,{},zgc);_.mb=function Agc(){var b,c,d,e,f,g;this.a=new RMb(40,PDb(this.D.n),1,10000);o2b(this.a._,700,180,-500);A4b(this.F,new q4b(16448250,1000,10000));this.b=new Ytb(this.a,this.D.b);q2b(this.b.v,150);b=new SUb(16777215,1.475);o2b(b._,100,100,-100);SLb(this.F,b);c=new _Ub(16777215,16777215,1.25);v_b(c.L,0.6,1,0.75);v_b(c.a,0.1,0.8,0.7);F1b(c._,500);SLb(this.F,c);g=new J$b((Ggc(),Fgc));SVb(g,(FXb(),CXb));rFb(HVb(g),fHc,new yJb((RJb(),CJb),new z_b(30719)));rFb(HVb(g),gHc,new yJb(CJb,new z_b(16777215)));rFb(HVb(g),fHc,new yJb(CJb,o_b(c.L)));rFb(HVb(g),'offset',new yJb(DJb,new fhb(400)));rFb(HVb(g),'exponent',new yJb(DJb,new fhb(0.6)));l4b(this.F.b,o_b(Au(Au(oOb(HVb(g).i,gHc),174).d,241)));f=new hTb(4000,32,15);e=new R3b(f,g);SLb(this.F,e);kEb(this.D.n,this.F.b.c,1);this.D.n.$=true;this.D.n._=true;d=new fqc;try{Wpc(d,'./static/models/obj/lightmap/lightmap.js',new Dgc(this,d))}catch(a){a=hR(a);if(Du(a,46)){GLb();kU(FLb,(zrb(),xrb),KGc)}else throw gR(a)}};_.nb=function Bgc(a){Wtb(this.b);_Db(this.D.n,this.F,this.a,null,false)};cS(1101,1,{},Dgc);_.vf=function Egc(){var a;a=new R3b(this.b.a,new uYb(this.b.b));n2b(a._,0);n2b(a.eb,100);SLb(this.a.F,a)};var Fgc;cS(1102,1,{},Kgc);_.Md=function Lgc(){return Tgc(),Igc};_.Nd=function Mgc(){return Ugc(),Jgc};var Igc,Jgc;cS(1103,1,{},Ogc);_.bc=function Pgc(){return 'uniform vec3 topColor;\nuniform vec3 bottomColor;\nuniform float offset;\nuniform float exponent;\n\nvarying vec3 worldPosition;\n\nvoid main() {\n\n\tfloat h = normalize( worldPosition + offset ).y;\n\tgl_FragColor = vec4( mix( bottomColor, topColor, max( pow( h, exponent ), 0.0 ) ), 1.0 );\n\n}'};cS(1104,1,{},Rgc);_.bc=function Sgc(){return 'varying vec3 worldPosition;\n\nvoid main() {\n\n\tvec4 mPosition = modelMatrix * vec4( position, 1.0 );\n\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n\tworldPosition = mPosition.xyz;\n\n}'};var eM=Vgb($Fc,'MaterialsLightmap$DemoScene',1100),dM=Vgb($Fc,'MaterialsLightmap$DemoScene$1',1101),HI=Vgb(hHc,'MeshFaceMaterial',899),hM=Vgb($Fc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator',1102),fM=Vgb($Fc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator$1',1103),gM=Vgb($Fc,'MaterialsLightmap_Resources_default_InlineClientBundleGenerator$2',1104);qBc(wi)(18);