function Ooc(){}
function Zoc(){}
function Woc(){}
function cpc(){}
function bpc(){}
function gpc(){}
function fpc(){}
function CEb(a,b){a.f=b}
function Qoc(){S7b.call(this)}
function Voc(){Voc=rLc;Uoc=new Zoc}
function jpc(){jpc=rLc;Xoc=new cpc}
function kpc(){kpc=rLc;Yoc=new gpc}
function bFb(a,b){!a.b&&(a.b=new gQb);a.b.qd(RNc,b)}
function Poc(a){var b,c,d;d=new _mb;for(b=0;b<a.n.Sc();++b){c=ir(a.n.Kc(b),179);c.gC()==ZB?Qmb(d,b,new Cnb(_q(mM,{88:1,106:1},194,[new xUb(1,0,0,0),new xUb(0,1,0,0),new xUb(0,0,1,0)]))):Qmb(d,b,new Cnb(_q(mM,{88:1,106:1},194,[new xUb(1,0,0,1),new xUb(1,1,0,1),new xUb(0,1,0,1),new xUb(0,0,0,1)])))}return d}
function Y6b(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z;k=new _mb;i=new _mb;j=new _mb;for(n=0,o=a.j.c;n<o;++n){Pmb(i,new _mb)}for(n=0,o=a.k.c;n<o;++n){Pmb(j,new _mb)}for(n=0,o=a.n.Sc();n<o;++n){f=ir(a.n.Kc(n),179);if(f.gC()==$B){b=f.c;c=f.d;d=f.e;e=ir(f,180).b;r=new LPb(0,0,0);s=new LPb(0,0,0);cOb(r.g,f.g);cOb(s.g,f.g);EPb(r,f.i);EPb(s,f.i);r.c=b;r.d=c;r.e=e;s.c=c;s.d=d;s.e=e;if(f.o.Sc()==4){r.o.Rc(0,new mOb(ir(f.o.Kc(0),178).d));r.o.Rc(1,new mOb(ir(f.o.Kc(1),178).d));r.o.Rc(2,new mOb(ir(f.o.Kc(3),178).d));s.o.Rc(0,new mOb(ir(f.o.Kc(1),178).d));s.o.Rc(1,new mOb(ir(f.o.Kc(2),178).d));s.o.Rc(2,new mOb(ir(f.o.Kc(3),178).d))}ar(k.b,k.c++,r);ar(k.b,k.c++,s);for(p=0,q=a.k.c;p<q;++p){if(ir(Tmb(a.k,p),117).Sc()>0){x=ir(ir(Tmb(a.k,p),117).Kc(n),117);t=ir(x.Kc(0),189);u=ir(x.Kc(1),189);v=ir(x.Kc(2),189);w=ir(x.Kc(3),189);y=new Cnb(_q(jM,{88:1,106:1,190:1},189,[new XSb(t.b,t.c),new XSb(u.b,u.c),new XSb(w.b,w.c)]));z=new Cnb(_q(jM,{88:1,106:1,190:1},189,[new XSb(u.b,u.c),new XSb(v.b,v.c),new XSb(w.b,w.c)]));ir((Qbb(p,j.c),j.b[p]),117).Hc(y);ir((Qbb(p,j.c),j.b[p]),117).Hc(z)}}for(p=0,q=a.j.c;p<q;++p){if(ir(Tmb(a.j,p),117).Sc()>0){g=ir(ir(Tmb(a.j,p),117).Kc(n),189);ir((Qbb(p,i.c),i.b[p]),117).Hc(g);ir((Qbb(p,i.c),i.b[p]),117).Hc(g)}}}else{ar(k.b,k.c++,f);for(p=0,q=a.j.c;p<q;++p){ir((Qbb(p,i.c),i.b[p]),117).Hc(ir(ir(Tmb(a.j,p),117).Kc(n),189))}for(p=0,q=a.k.c;p<q;++p){ir((Qbb(p,j.c),j.b[p]),117).Hc(ir(ir(Tmb(a.k,p),117).Kc(n),117))}}}a.n=k;a.j=i;a.k=j;NOb(a);OOb(a,(Keb(),Keb(),Ieb));ROb(a);a.R.b&&QOb(a)}
_=Joc.prototype;_.zb=function Noc(){O7b(this.c,new Qoc(this.b))};_=Qoc.prototype=Ooc.prototype=new R7b;_.gC=function Roc(){return JH};_.nb=function Soc(){var a,b,c,d,e,f,g,i,j,k,n;this.b=new SNb(40,NDb(this.D.o),1,2000);this.b.X.c=800;d=new YXb(150,150,150);e=new YXb(150,150,150);f=new YXb(150,150,150);Y6b(f);g=new l2b;g.i=true;this.c=new K5b(d,g);this.c.X.d=0;TMb(this.E,this.c);b=new DEb((WEb(),VEb),Poc(e));CEb(b,(LEb(),JEb));j=new W4b((Voc(),Uoc));bFb(Z_b(j),b);this.e=new K5b(e,j);this.e.X.d=300;TMb(this.E,this.e);c=new DEb(VEb,Poc(f));CEb(c,JEb);k=new W4b(Uoc);bFb(Z_b(k),c);this.f=new K5b(f,k);this.f.X.d=-300;TMb(this.E,this.f);n=new OYb(75,32,16);a=new DEb(VEb,Poc(n));CEb(a,JEb);i=new W4b(Uoc);bFb(Z_b(i),a);this.d=new K5b(n,i);this.d.X.d=0;TMb(this.E,this.d)};_.ob=function Toc(a){this.c.$.d+=0.005;this.c.$.e+=0.01;this.e.$.d+=0.005;this.e.$.e+=0.01;this.f.$.d+=0.005;this.f.$.e+=0.01;if(this.d){this.d.$.d+=0.005;this.d.$.e+=0.01}SDb(this.D.o,this.E,this.b,null,false)};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;var Uoc;_=Zoc.prototype=Woc.prototype=new Jb;_.gC=function $oc(){return MH};_.Pd=function _oc(){return jpc(),Xoc};_.Qd=function apc(){return kpc(),Yoc};var Xoc=null,Yoc=null;_=cpc.prototype=bpc.prototype=new Jb;_.gC=function dpc(){return KH};_._b=function epc(){return '#extension GL_OES_standard_derivatives : enable\r\n\r\nvarying vec4 vCenter;\r\n\r\nfloat edgeFactorTri() {\r\n\r\n\tvec3 d = fwidth( vCenter.xyz );\r\n\tvec3 a3 = smoothstep( vec3( 0.0 ), d * 1.5, vCenter.xyz );\r\n\treturn min( min( a3.x, a3.y ), a3.z );\r\n\r\n}\r\n\r\nfloat edgeFactorQuad1() {\r\n\r\n\tvec2 d = fwidth( vCenter.xy );\r\n\tvec2 a2 = smoothstep( vec2( 0.0 ), d * 1.5, vCenter.xy );\r\n\r\n\treturn min( a2.x, a2.y );\r\n\r\n}\r\n\r\nfloat edgeFactorQuad2() {\r\n\r\n\tvec2 d = fwidth( 1.0 - vCenter.xy );\r\n\tvec2 a2 = smoothstep( vec2( 0.0 ), d * 1.5, 1.0 - vCenter.xy );\r\n\r\n\treturn min( a2.x, a2.y );\r\n}\r\n\r\nvoid main() {\r\n\r\n\tif ( vCenter.w == 0.0 ) {\r\n\r\n\t\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), edgeFactorTri() );\r\n\r\n\t} else {\r\n\r\n\t\tgl_FragColor.rgb = mix( vec3( 1.0 ), vec3( 0.2 ), min( edgeFactorQuad1(), edgeFactorQuad2() ) );\r\n\r\n\t}\r\n\r\n\tgl_FragColor.a = 1.0;\r\n\r\n}\r\n'};_=gpc.prototype=fpc.prototype=new Jb;_.gC=function hpc(){return LH};_._b=function ipc(){return 'attribute vec4 center;\r\nvarying vec4 vCenter;\r\n\r\nvoid main() {\r\n\r\n\tvCenter = center;\r\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\r\n\r\n}\r\n'};var JH=xfb(iPc,'MaterialsWireframe$DemoScene',qE),mM=wfb(IPc,'Vector4;',xC),MH=xfb(iPc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator',gy),KH=xfb(iPc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$1',gy),LH=xfb(iPc,'MaterialsWireframe_Resources_default_InlineClientBundleGenerator$2',gy);ILc(ge)(36);