function YHb(){}
function EIb(){}
function IIb(){}
function HIb(){}
function LIb(){}
function PIb(){}
function OIb(){}
function RUb(){}
function SUb(){zQb.call(this)}
function ZHb(a){$Hb.call(this,a)}
function FIb(){ZHb.call(this,new IIb)}
function MIb(){ZHb.call(this,new PIb)}
function $Hb(a){var b,c,d,e,f,g,i,j,k,n,o,p,q;Mzb.call(this);for(f=0;f<=20;++f){q=f/20;for(g=0;g<=20;++g){j=g/20;i=a.me(j,q);this.H.Cc(i)}}for(f=0;f<20;++f){for(g=0;g<20;++g){b=f*21+g;c=f*21+g+1;d=(f+1)*21+g;e=(f+1)*21+g+1;k=new lCb(f/20,g/20);n=new lCb(f/20,(g+1)/20);o=new lCb((f+1)/20,g/20);p=new lCb((f+1)/20,(g+1)/20);this.q.Cc(new GAb(b,c,e,d));hr(S8(this.p,0),114).Cc(new z9($q(lG,{89:1,107:1,156:1},155,[k,n,o,p])))}}Azb(this);Bzb(this,(O2(),O2(),M2));Ezb(this)}
var uac='thothbot.parallax.core.shared.geometries.parametric.';_=YHb.prototype=new qzb;_.gC=function _Hb(){return lB};_=FIb.prototype=EIb.prototype=new YHb;_.gC=function GIb(){return vB};_=IIb.prototype=HIb.prototype=new Tb;_.gC=function JIb(){return uB};_.me=function KIb(a,b){var c,d,e;a*=3.141592653589793;b*=6.283185307179586;a=a*2;if(a<3.141592653589793){c=3*Math.cos(a)*(1+Math.sin(a))+2*(1-Math.cos(a)/2)*Math.cos(a)*Math.cos(b);e=-8*Math.sin(a)-2*(1-Math.cos(a)/2)*Math.sin(a)*Math.cos(b)}else{c=3*Math.cos(a)*(1+Math.sin(a))+2*(1-Math.cos(a)/2)*Math.cos(b+3.141592653589793);e=-8*Math.sin(a)}d=-2*(1-Math.cos(a)/2)*Math.sin(b);return new bDb(c,d,e)};_=MIb.prototype=LIb.prototype=new YHb;_.gC=function NIb(){return xB};_=PIb.prototype=OIb.prototype=new Tb;_.gC=function QIb(){return wB};_.me=function RIb(a,b){var c,d,e,f;a=a-0.5;c=6.283185307179586*b;d=Math.cos(c)*(2+a*Math.cos(c/2));e=Math.sin(c)*(2+a*Math.cos(c/2));f=a*Math.sin(c/2);return new bDb(d,e,f)};_=MUb.prototype;_.qb=function QUb(){vQb(this.b,new SUb(this.a))};_=SUb.prototype=RUb.prototype=new yQb;_.gC=function TUb(){return fD};_.qd=function UUb(){jdb(this,new Uyb(45,beb(this.A.C),1,2000))};_.hb=function VUb(){var a,b,c,d,e,f,g;this.z.D.d=400;eyb(this.B,this.z);eyb(this.B,new mJb(4210752));c=new pJb(16777215);YCb(c.D,0,0,1);eyb(this.B,c);e=new Y8;d=new DLb;ALb(d,(yPb(),APb(rac,(nxb(),mxb),null)));wLb(d,new mzb(12303291));_q(e.a,e.b++,d);b=new QKb;LKb(b,new mzb(16777215));b.g=true;b.M=true;b.N=0.1;_q(e.a,e.b++,b);f=RPb(new FIb,e);a=hr(S8(f.u,0),201);a.b=(O2(),O2(),N2);YCb(f.Bd(),0,0,0);f.I.de(20);eyb(this.B,f);g=RPb(new MIb,e);YCb(g.Bd(),10,0,0);g.I.de(100);eyb(this.B,g)};_.pd=function WUb(){};_.ib=function XUb(a){var b,c,d;uCb(this.z.D,Math.cos(a*1.0E-4)*800);$Cb(this.z.D,Math.sin(a*1.0E-4)*800);yyb(this.z,this.B.D);for(b=0,c=this.B.u.b;b<c;++b){d=hr(S8(this.B.u,b),194);d.Cd().c+=0.01;d.Cd().d+=0.005}};var lB=$2(sac,'Parametric'),vB=$2(uac,'Klein'),uB=$2(uac,'Klein$1'),xB=$2(uac,'Mobius'),wB=$2(uac,'Mobius$1'),fD=$2(dac,'GeometriesParametric$DemoScene');D6b(be)(7);